# Name:	Junxiang Wen
# Last Edited: 10/13/2019
# Topic:     Project 2: Pseudocode for Implementing a Linux Shell
# make file
myshell: myshell.c utility.c myshell.h
	gcc -Wall myshell.c utility.c -o myshell
